# Site settings
name: org-trello
trace: false
safe: true
highlighter: rouge

encoding: utf-8

title: org-trello
email: eniotna.t@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  org-trello is an emacs minor mode to extend org-mode with trello abilities.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://org-trello.github.io" # the base hostname & protocol for your site
twitter_username: ardumont
github_username:  ardumont

# Build settings
markdown: kramdown
